# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Propensity Score Matching
#' @return A list with match_id and match_x
#' @param
#' x is the input vector to the function
#' @examples
#' set.seed(199)
#' x<-runif(10)
#' ps_match3(x)
#' @export
ps_match3 <- function(x) {
    .Call(`_egpkg_ps_match3`, x)
}

#' Hello world from Rcpp
#' @return A list with two vectors (`x`, `y`).
#' @examples
#' rcpp_hello_world()
#' @export
rcpp_hello_world <- function() {
    .Call(`_egpkg_rcpp_hello_world`)
}

